### ISSUE TITLE
actively developed?

### ISSUE THREAD

**Issue by cuechan** [Souryo/proxer-rs#1]
Wird die Library noch aktiv entwickelt?
Wenn ja, würde ich fragen, ob interesse besteht, meine [proxer-rs lib](https://github.com/cuechan/proxer-rs) und deine vllt. zusammen als eine einzelne weiter zu entwickeln?
Gruß Cuechan

**Comment by Ceeox** [comment]
Naja, aktiv sieht etwas anders aus, aber ja, hätte durchaus interesse an einer bzw. an einer zusammen gelegten Library zu arbeiten.

**Comment by cuechan** [comment]
Nice, du hast ja vermutlich auch einen Proxer Account. Hast du zufällig Lust mir deinen Usernamezu verraten? Dann kann man da ja mal ein bisschen schreiben und schauen, wie man das umsetzen könnte. 
Meiner ist der selbe wie hier.

**Comment by Ceeox** [comment]
Oke, is der selbe wie hier: Souryo. Hab dir in Proxer schon mal ne pm geschickt.

**Comment by Ceeox** [comment]
@cuechan kein Interesse mehr? Da ich seit einem Monat auf eine Antwort von dir warte…
